# Generated by Django 3.1.7 on 2021-05-24 21:53

import apps.app_login_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, validators=[apps.app_login_register.models.ValidarLongitudMinima])),
                ('last_name', models.CharField(max_length=45, validators=[apps.app_login_register.models.ValidarLongitudMinima])),
                ('birth_date', models.DateField(validators=[apps.app_login_register.models.validarFecha])),
                ('email', models.CharField(max_length=50, validators=[apps.app_login_register.models.validarEmail])),
                ('password', models.CharField(max_length=100, validators=[apps.app_login_register.models.ValidarLongitudPassword])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
