# Generated by Django 3.1.7 on 2021-05-18 08:46

import apps.app_login_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login_register', '0003_auto_20210518_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45, validators=[apps.app_login_register.models.ValidarLongitudMinima]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
    ]
