# Generated by Django 3.1.7 on 2021-05-20 00:33

import apps.app_login_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login_register', '0004_auto_20210518_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(validators=[apps.app_login_register.models.validarFecha]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, validators=[apps.app_login_register.models.validarEmail]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45, validators=[apps.app_login_register.models.ValidarLongitudMinima]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[apps.app_login_register.models.ValidarLongitudPassword]),
        ),
    ]
