# Generated by Django 3.1.7 on 2021-05-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login_register', '0005_auto_20210519_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
